[package]
name = "leader_election"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
uuid = { version = "0.8", features = ["v4"] }
